# Generated by Django 5.2 on 2025-11-17 01:41

import cloudinary.models
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                ("idCarrera", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("cantidadAno", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "Carreras",
                "db_table": "Carrera",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("idUsuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombreYapellido", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_activate", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Usuarios",
                "db_table": "Usuario",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Foro",
            fields=[
                ("idForo", models.AutoField(primary_key=True, serialize=False)),
                ("pregunta", models.TextField()),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foros",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Foros",
                "db_table": "Foro",
            },
        ),
        migrations.CreateModel(
            name="ForoArchivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="archivo"
                    ),
                ),
                (
                    "foro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos",
                        to="app.foro",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Archivos de Foros",
                "db_table": "ForoArchivo",
            },
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                ("idMateria", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materias",
                        to="app.carrera",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Materias",
                "db_table": "Materia",
            },
        ),
        migrations.AddField(
            model_name="foro",
            name="materia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="foros",
                to="app.materia",
            ),
        ),
        migrations.CreateModel(
            name="Respuesta",
            fields=[
                ("idRespuesta", models.AutoField(primary_key=True, serialize=False)),
                ("respuesta_texto", models.TextField(blank=True, null=True)),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("total_likes", models.IntegerField(default=0)),
                ("total_dislikes", models.IntegerField(default=0)),
                ("total_votos", models.IntegerField(default=0)),
                ("puntaje_neto", models.IntegerField(default=0)),
                (
                    "foro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="app.foro",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="app.materia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Respuestas",
                "db_table": "Respuesta",
            },
        ),
        migrations.CreateModel(
            name="RespuestaArchivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="archivo"
                    ),
                ),
                (
                    "respuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos",
                        to="app.respuesta",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Archivos de Respuestas",
                "db_table": "RespuestaArchivo",
            },
        ),
        migrations.CreateModel(
            name="Puntaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.SmallIntegerField(
                        choices=[(1, "like"), (-1, "dislike"), (0, "none")], default=0
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puntajes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "respuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puntajes",
                        to="app.respuesta",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Puntajes",
                "db_table": "Puntaje",
                "unique_together": {("usuario", "respuesta")},
            },
        ),
    ]
