# Generated by Django 5.2 on 2025-11-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foroarchivo",
            name="hash",
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="respuestaarchivo",
            name="hash",
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="foroarchivo",
            unique_together={("foro", "hash")},
        ),
        migrations.AlterUniqueTogether(
            name="respuestaarchivo",
            unique_together={("respuesta", "hash")},
        ),
    ]
