# Generated by Django 5.2.7 on 2025-10-21 20:19

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_foro_fecha_actualizacion_foro_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foro',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='respuestadetalle',
            name='archivo',
        ),
        migrations.AlterField(
            model_name='foro',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ForoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='archivo')),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='app.foro')),
            ],
            options={
                'verbose_name_plural': 'Archivos de Foros',
                'db_table': 'ForoArchivo',
            },
        ),
        migrations.CreateModel(
            name='RespuestaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='archivo')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='app.respuesta')),
            ],
            options={
                'verbose_name_plural': 'Archivos de Respuestas',
                'db_table': 'RespuestaArchivo',
            },
        ),
    ]
