# Generated by Django 5.2.7 on 2025-10-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_foro_archivo_remove_respuestadetalle_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='ano',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
    ]
