# Generated by Django 5.2.7 on 2025-11-03 21:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_materia_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='puntaje',
        ),
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to='app.respuesta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Puntajes',
                'db_table': 'Puntaje',
            },
        ),
    ]
